# Generated by Django 5.0.7 on 2024-07-18 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Login",
            new_name="Home",
        ),
    ]
